apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: elevation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "81"
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
              claimName: elevation-pvc
      containers:
        - name: api
          image: ghcr.io/dzfranklin/elevation-api:latest
          env:
            - name: METRICS_PORT
              value: "81"
            - name: DEM_SOURCE
              value: /data/index.gti.gpkg
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /health
              port: http
