apiVersion: apps/v1
kind: Deployment
metadata:
  name: elevation-api
  namespace: pt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elevation-api
  template:
    metadata:
      labels:
        app: elevation-api
    spec:
      containers:
        - name: elevation-api
          image: ghcr.io/dzfranklin/elevation-api:latest
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: APP_ENV
              value: "production"
            - name: ELEVATION_DATASET
              value: "/data/cop90/index.vrt"
            - name: RUST_LOG
              value: "info"
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: http
      volumes:
        - name: data
          hostPath:
            path: /elevation_data
