apiVersion: v1
kind: PersistentVolume
metadata:
  name: elevation-pv
  namespace: elevation
spec:
  capacity:
    storage: 100Gi # unused by localPath provisioner
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/elevation_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elevation-pvc
  namespace: elevation
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: elevation-pv
